### ISSUE TITLE
Portal generates in the middle of the void

### ISSUE THREAD

**Issue by MikroChris** [Axanthic-Game-Studios/Lands-of-Icaria#16]
Hi, I don't know if it was ment to be that way, but I created a portal and spawned in the middle of nothing
It would be nice if there generates a platform to prevent this but idk

Also It's kinda hard to lit the portal with the grenades :(

![2024-08-25_12 59 03](https://github.com/user-attachments/assets/0f9ad59c-f2e0-4634-a821-09cd287707d3)

**Comment by MikroChris** [comment]
The version is 1.20.1-2.0.1.0

**Comment by luxtracon** [comment]
Hey, sorry for your inconviences. That's not the way it's meant to be. There is a small chance, depending on your world seed, for the portal to generate mid air and there is little we can do to prevent it, we already improved on this massively compared to versions on 1.12.2. We had plenty of test worlds and never run into this so far, also no other reports of this from other players so far, likely really unlucky in your case. Nonetheless, there should be a platform generating beneath the portal, that is clearly missing, we will look into that.

Could you provide me with the seed of this world and the position the portal is located at (either at the overworld or in the dimension, that doesn't matter)?

Grenades were kinda hard to use to ignite the portal on 1.20.1. We also massively improved on this with 1.21! You can join our Discord and take a look into the help and support channel, there is a video showing, how it is easier to ignite the portal on 1.20.1.

**Comment by MikroChris** [comment]
The seed is: -8191960189795131328, could it be that the world was a superflat typo world with no structures allowed to spawn, maybe?
The portal in Icaria was exactly placed at 0 0 0, in the overworld is at 54 167 -15

Also will there be more updates for 1.20.1?

**Comment by luxtracon** [comment]
Superflat and structures turned off would have no effect whether the portal spawns correct or not. I tried to reproduce this issue with your seed, settings and the overworld portal placed at the give locations, but for me the portal in Icaria was placed on the surface as intended.

Does this issue occur more often if you create other maps too or was it just this one time?

**Comment by MikroChris** [comment]
This was the only time it happened

Maybe because I have more mods installed, I have read that some mods from MCreator break world generation

**Comment by luxtracon** [comment]
That could be a reason contributing to the issue. If you could provide a full mod list of mods you used in combination with Icaria when the issue occured, I could try to figure out which mod might cause compatibility issues and try to fix the issue on our end, if that's possible. Other than that I don't see anything I can fix on our end now and would mark the issue as closed for now. Also to answer your question, we are not planning to push any further updates for 1.20.1, only critical bug fixes if needed. We want to focus on 1.21 and onwards, and since we are a pretty small team, working on multiple versions at the same time isn't really feasible for us.
